### ISSUE TITLE
Blank window on desktop screen

### ISSUE THREAD

**Issue by EtXetera** [MishaProductions/Rectify11Installer#156]
### Description

first, i'm newbie. and i dont know what is this. blank window appears everytime i run an app. then dissappear in few minutes. 

### Steps To Reproduce

.

### Rectify11 Version

version3 rp3

### Windows Version

Windows 11 22H2 25346.1001

### Logs

https://github.com/MishaProductions/Rectify11Installer/assets/134760071/3360437c-0f12-4cf1-948f-98f4481723f1

**Comment by EtXetera** [comment]
i tried uninstalling MFE and the problem is solved.

**Comment by evansidhu** [comment]
Looks like the Mica app by firecube, maybe mica for everyone is creating a conflict with that app, try checking if mica is installed, and if it is, maybe uninstall and only use mica for everyone, if it is not installed, reinstall mica for everyone anc check if the problem is solved, if it is, please close the issue.

**Comment by EtXetera** [comment]
i'm sorry. i forgot to close this issue. i used the latest MFE and even try older version and still facing the same issue. so i don't use MFE at all. thank you for ur reply
