### ISSUE TITLE
(Bug) Opening some directories in explorer such as desktop or pictures crashes the explorer, Xbox game bar and game clips (captures) do not work/launch

### ISSUE THREAD

**Issue by es1228** [MishaProductions/Rectify11Installer#163]
Hello, I am running the latest build, and I would like to file a bug.
The bug is that sometimes opening directories in explorer can crash the whole explorer, opening in cmd works fine.
It is a minor issue, but is really annoying if you want to open or save a file to the directories, I hope it gets fixed in the near future.
Also, Xbox game bar and captures do not work, which means I cannot screen record
Otherwise, great job by the team for this amazing project.

**Comment by evansidhu** [comment]
Problem was that it did not launch, also because some directories crashed the explorer and sometimes just by clicking a taskbar icon the system broke itself, I just uninstalled, maybe I will come back if this gets fixed or maybe in the final build, for now i'm only using the themes, and they work fine except for the control panel where the "adjust your computers settings" and side panel were colored white for some reason, overall still a great and promising project and I look forward to the release.

**Comment by Typical0** [comment]
Well, instability with Rectify11 is thing. I've also used it before and yes, it crashed a couple of times. If you want a stable experience, go with Basic set and not Basic + Advanced.

**Comment by evansidhu** [comment]
> Well, instability with Rectify11 is thing. I've also used it before and yes, it crashed a couple of times. If you want a stable experience, go with Basic set and not Basic + Advanced.

Do you mean the icon pack?

**Comment by es1228** [comment]
I fixed it my manually changing some icons for executable shortcuts myself and not using the installer to change any icons.
